// Pure markdown-generation logic for a ticker's vault history note
// (TICKER-history.md), split out from noteSync.ts so it can be unit tested
// without pulling in the real "obsidian" package (noteSync.ts's
// `instanceof TFile` check needs the genuine runtime class Obsidian injects,
// which has no standalone implementation outside the app — importing it at
// all breaks under vitest).
import { HistoryEntry, historyIv, SavedValuation } from "./valuationStore";
import { formatCurrency, formatPercent } from "./format";
import { marginOfSafety } from "./calculations";

// Where a ticker's history note lives: <folder>/<TICKER>-history.md, or just
// <TICKER>-history.md at the vault root when the folder is blank. Same
// fixed-by-ticker naming as research notes' TICKER-research.md.
export function historyNotePath(folder: string, ticker: string): string {
	const trimmed = folder.trim().replace(/\/+$/, "");
	const filename = `${ticker}-history.md`;
	return trimmed ? `${trimmed}/${filename}` : filename;
}

// One ticker's whole valuation history as a markdown table — one row per
// HistoryEntry (i.e. per saved valuation or price refresh, at most one per
// calendar day), newest first. MoS is derived from each entry's stored IV
// and price, the same way the in-app history table does it, never stored.
// Rewritten in full whenever this ticker's record changes; no other
// ticker's note is touched.
export function buildHistoryNoteContent(ticker: string, record: SavedValuation): string {
	const lines = [
		`# ${ticker} — valuation history`,
		"",
		`Auto-generated by the Stock Valuations plugin: one row per saved valuation or price refresh (at most one per day), newest first. Rewritten whenever ${ticker} is saved, refreshed, or its history is edited in the plugin, so hand-edits here won't stick.`,
		"",
	];

	const entries = [...(record.history ?? [])].sort((a, b) => b.at - a.at);
	if (entries.length === 0) {
		lines.push("_No history yet — it starts with the next Save or price refresh._");
		return lines.join("\n") + "\n";
	}

	lines.push(
		"| Date | Price | DCF Bear | DCF Base | DCF Bull | Reverse DCF | Ten Cap | Graham Bear | Graham Base | Graham Bull | DDM Bear | DDM Base | DDM Bull |",
		"|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|"
	);
	for (const e of entries) {
		const cell = (iv: number | null | undefined) => ivMosCell(historyIv(iv), e.price);
		lines.push(
			`| ${window.moment(e.at).format("YYYY-MM-DD")} | ${formatCurrency(e.price)} | ${cell(e.dcfBearIv)} | ${cell(
				e.dcfBaseIv
			)} | ${cell(e.dcfBullIv)} | ${formatPercent(historyIv(e.impliedGrowth) * 100)} | ${cell(e.tenCapIv)} | ${cell(
				e.grahamBearIv
			)} | ${cell(e.grahamBaseIv)} | ${cell(e.grahamBullIv)} | ${cell(e.ddmBearIv)} | ${cell(e.ddmBaseIv)} | ${cell(
				e.ddmBullIv
			)} |`
		);
	}

	return lines.join("\n") + "\n";
}

// Packs IV and MoS into one cell ("$164/-33%"), same convention as the
// in-app tables' ivMosFormatter.
function ivMosCell(iv: number, price: HistoryEntry["price"]): string {
	return `${formatCurrency(iv)}/${formatPercent(marginOfSafety(iv, price))}`;
}
