import { App, TFile } from "obsidian";
import { ValuationTable } from "./valuationStore";
import { formatCurrency, formatPercent } from "./format";

// Regenerates the whole note from scratch on every call — this is the vault-
// visible mirror of the plugin's own data, not something meant to be hand-edited.
export async function syncValuationsNote(app: App, path: string, valuations: ValuationTable): Promise<void> {
	const content = buildNoteContent(valuations);
	const existing = app.vault.getAbstractFileByPath(path);
	if (existing instanceof TFile) {
		await app.vault.modify(existing, content);
		return;
	}
	await ensureFolderExists(app, path);
	await app.vault.create(path, content);
}

async function ensureFolderExists(app: App, filePath: string): Promise<void> {
	const folderPath = filePath.split("/").slice(0, -1).join("/");
	if (!folderPath) return;
	if (app.vault.getAbstractFileByPath(folderPath)) return;
	await app.vault.createFolder(folderPath).catch(() => {
		// Already exists or created concurrently — fine either way.
	});
}

function buildNoteContent(valuations: ValuationTable): string {
	const tickers = Object.keys(valuations).sort();

	const lines = [
		"# Stock Valuations",
		"",
		"Auto-generated by the Stock Valuations plugin. Add, edit, or remove rows from the plugin's calculator — this note is overwritten on every save, so hand-edits here won't stick.",
		"",
	];

	if (tickers.length === 0) {
		lines.push("_No valuations saved yet._");
		return lines.join("\n") + "\n";
	}

	lines.push(
		"| Symbol | DCF MoS | DCF IV | Ten Cap MoS | Ten Cap IV | Ten Cap Yield | Graham MoS | Graham IV | Price | Updated |",
		"|---|---:|---:|---:|---:|---:|---:|---:|---:|---|"
	);

	for (const ticker of tickers) {
		const v = valuations[ticker];
		const r = v.results;
		const price = parseFloat(v.state.price) || 0;
		lines.push(
			`| ${ticker} | ${formatPercent(r.dcfMos)} | ${formatCurrency(r.dcfIv)} | ${formatPercent(
				r.tenCapMos
			)} | ${formatCurrency(r.tenCapIv)} | ${formatPercent(r.tenCapYield)} | ${formatPercent(
				r.grahamMos
			)} | ${formatCurrency(r.grahamIv)} | ${formatCurrency(price)} | ${window.moment(v.updatedAt).format(
				"YYYY-MM-DD"
			)} |`
		);
	}

	return lines.join("\n") + "\n";
}
