// Pure markdown-generation logic for the vault summary note, split out from
// noteSync.ts so it can be unit tested without pulling in the real "obsidian"
// package (noteSync.ts's `instanceof TFile` check needs the genuine runtime
// class Obsidian injects, which has no standalone implementation outside the
// app — importing it at all breaks under vitest).
import { ValuationTable } from "./valuationStore";
import { formatCurrency, formatPercent } from "./format";

export function buildNoteContent(valuations: ValuationTable, includeResearchColumn: boolean): string {
	const tickers = Object.keys(valuations).sort();

	const lines = [
		"# Stock Valuations",
		"",
		"Auto-generated by the Stock Valuations plugin. Add, edit, or remove rows from the plugin's calculator — this note is overwritten on every save, so hand-edits here won't stick.",
		"",
	];

	if (tickers.length === 0) {
		lines.push("_No valuations saved yet._");
		return lines.join("\n") + "\n";
	}

	if (includeResearchColumn) {
		lines.push(
			"| Symbol | DCF Bear | DCF Base | DCF Bull | Ten Cap | Ten Cap Yield | Graham Bear | Graham Base | Graham Bull | Price | Updated | Research |",
			"|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|---|"
		);
	} else {
		lines.push(
			"| Symbol | DCF Bear | DCF Base | DCF Bull | Ten Cap | Ten Cap Yield | Graham Bear | Graham Base | Graham Bull | Price | Updated |",
			"|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|"
		);
	}

	for (const ticker of tickers) {
		const v = valuations[ticker];
		const { bear, base, bull } = v.scenarios;
		const price = parseFloat(base.state.price) || 0;
		let row =
			`| ${ticker} | ${ivMosCell(bear.results.dcfIv, bear.results.dcfMos)} | ${ivMosCell(
				base.results.dcfIv,
				base.results.dcfMos
			)} | ${ivMosCell(bull.results.dcfIv, bull.results.dcfMos)} | ${ivMosCell(
				base.results.tenCapIv,
				base.results.tenCapMos
			)} | ${formatPercent(base.results.tenCapYield)} | ${ivMosCell(
				bear.results.grahamIv,
				bear.results.grahamMos
			)} | ${ivMosCell(base.results.grahamIv, base.results.grahamMos)} | ${ivMosCell(
				bull.results.grahamIv,
				bull.results.grahamMos
			)} | ${formatCurrency(price)} | ${window.moment(v.updatedAt).format("YYYY-MM-DD")} |`;
		if (includeResearchColumn) {
			row += ` ${researchLinkCell(v.researchNotePath)} |`;
		}
		lines.push(row);
	}

	return lines.join("\n") + "\n";
}

// Packs IV and MoS into one cell ("$164/-33%"), same convention as the
// table's ivMosFormatter — keeps a 3-scenario x 2-method spread from doubling
// the column count on top of Ten Cap, price, and updated-at.
function ivMosCell(iv: number, mos: number): string {
	return `${formatCurrency(iv)}/${formatPercent(mos)}`;
}

// A bare wikilink built from the stored path — no reliance on ticker naming,
// so it works regardless of what the note is called or where it lives.
// Nothing about the note's contents is read here. The alias pipe is escaped
// as \| (not just any pipe already in the path) because this cell lives
// inside a markdown table row — an unescaped "|" reads as a new column and
// truncates the link right before "Research]]".
function researchLinkCell(path: string | undefined): string {
	if (!path) return "—";
	const target = path.replace(/\.md$/i, "").replace(/\|/g, "\\|");
	return `[[${target}\\|Research]]`;
}
